# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/prod'
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Assemble Distribution Files
      run: ./gradlew assembleDist
    #- name: Copy & Unpack Unpack Distribution Files
      #uses: alinz/ssh-scp-action@v0.1.1
      #with:
        #host: ${{ secrets.HOST }}
        #user: ${{ secrets.USERNAME }}
        #key: ${{ secrets.KEY }}
        #scp: ./build/distributions/MediaModBackendKotlin-1.0.0.zip ${{ secrets.USERNAME }}@${{ secrets.HOST }}:${{ SECRETS.DIR }}
        #ssh_after: |
            #cd ${{ secrets.DIR }} 
            #unzip -o MediaModBackendKotlin-1.0.0.zip 
            #rm -r MediaModBackendKotlin-1.0.0.zip
            #sudo /usr/bin/systemctl restart mediamodapi
